# Generated by Django 5.0.2 on 2024-03-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhiveapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Id', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('Condition', models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], max_length=200)),
                ('discription', models.TextField()),
                ('stock', models.CharField(choices=[('INSTOCK', 'INSTOCK'), ('OUTSTOCK', 'OUTSTOCK')], max_length=200)),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAFT', 'DRAFT')], max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookhiveapp.brand')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookhiveapp.catagories')),
                ('filterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookhiveapp.filterprice')),
            ],
        ),
    ]
